### ISSUE TITLE
2.10.0 not deployed on Maven Central

### ISSUE THREAD

**Issue by efge** [FasterXML/jackson-dataformats-text#148]
These artifacts are missing from Maven Central:
- com.fasterxml.jackson.dataformat:jackson-dataformat-properties:jar:2.10.0
- com.fasterxml.jackson.dataformat:jackson-dataformat-csv:jar:2.10.0
- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.10.0

**Comment by cowtowncoder** [comment]
Yes. This is due to problems with Sonatype OSSRH.

Please sign up for Jackson mailing list(s) dev, user or announce, or follow `@FasterXML` for release info. These will be used to communicate release status.
Full releases take 4+ hours even when everything goes smoothly and there is time window during which only incomplete set is available.

But on a bad day, like yesterday, the whole release process can go haywire when Sonatype's systems crash. This is what we had now.

Text dataformats were successfully released today and they are at Maven Central, finally.

**Comment by efge** [comment]
Apologies, I should have checked the lists first. Thanks.

**Comment by cowtowncoder** [comment]
No that is ok. Thank you for reporting it.

Also: now all components should be included; there were some problems with `jackson-annotations` jar, but Sonatype resolved it (https://issues.sonatype.org/browse/OSSRH-51881)
