### ISSUE TITLE
Converting properties with unicode characters to Json

### ISSUE THREAD

**Issue by abc-123-data** [FasterXML/jackson-dataformats-text#19]
I am trying to convert properties to Json and here is what I am seeing:

//String properties = "ƛ Ɯ Ɲ ƞ Ɵ Ơ ơ Ƣ = ƛ Ɯ Ɲ ƞ Ɵ Ơ ơ Ƣ";
String properties = "\u019B \u019C \u019D \u019E \u019F \u01A0 \u01A1 \u01A2 = \u019B \u019C \u019D \u019E \u019F \u01A0 \u01A1 \u01A2";
JsonNode node = new JavaPropsMapper().readValue(properties, JsonNode.class);
System.out.println(node.toString());

Expected output:
{"ƛ Ɯ Ɲ ƞ Ɵ Ơ ơ Ƣ" : "ƛ Ɯ Ɲ ƞ Ɵ Ơ ơ Ƣ"}

Observed output:
{"ƛ":"Ɯ Ɲ ƞ Ɵ Ơ ơ Ƣ = ƛ Ɯ Ɲ ƞ Ɵ Ơ ơ Ƣ"}

I am not sure if I am not using the library correctly or if I need to do more pre-processing of that String (maybe escape it or something?), or if its something else. Any help is appreciated.

**Comment by cowtowncoder** [comment]
Ok first things first: last line (`System.out.println(node.toString());`) is problematic for two reasons:

1. `JsonNode.toString()` is NOT designed to produce valid JSON and should only be used for diagnostics. What you can use instead is `System.out.println(mapper.writeValueAsString(node))`
2. Printing to console is not necessarily Unicode safe: you can not really determine correctness that way (`System.out` is just a byte stream so there's encoding by Jackson, as UTF-8, then decoding by console, then displaying results).

Having said that I don't know if that matters here: I assume the problem is that instead of splitting key and value at `=` sign, it would seem like it splits after first character, at space.
That does seem wrong.

Parsing itself is delegated to `Properties.load(Reader)`, so it should work according to official Properties file definition (that is, the way JDK deems it proper).

I will try to reproduce what you see to see if I can get more insight on this. Thank you for reporting it.

**Comment by abc-123-data** [comment]
Ah! You may have already solved my problem. I think I need to escape the spaces. Hold off on this while I test some more.

**Comment by cowtowncoder** [comment]
@abc-123-data Ok. I was thinking that spaces need not be quoted but now that you mention it... yeah. You may be right :)

**Comment by cowtowncoder** [comment]
Yes: say javadocs for `java.util.Properties`:

```
The key contains all of the characters in the line starting with the first non-white space character and up to, but not including, the first unescaped '=', ':', or white space character other than a line terminator. All of these key termination characters may be included in the key by escaping them with a preceding backslash character; for example,
```

**Comment by abc-123-data** [comment]
Thanks a lot. That was the problem!
