### ISSUE TITLE
Can't convert JsonNode to CSV using Jackson

### ISSUE THREAD

**Issue by g1ps** [FasterXML/jackson-dataformats-text#209]
Hi,

I've spent a week trying to achieve this, trawling through Javadocs and the various sites which provide examples but I can't for the life of me make it work. I've tried a range of things using CsvMapper. CsvSchema, ObjectBuilder and more, based on example code but they all seem to be based on trivial JSON read from a file. I have a complex JSON structure returned from a web API. I need to be able to handle nested data. I have the data in a JsonNode and can read elements from there and build CSV as a String, which works, but haven't made any progress at all with the Jackson facilities. It seems like there should be some elegant and simple way to parse the node into CSV, or any of the other available data types for that matter, if I could only find it but Jackson is a huge, very complex system and the examples don't work in my circumstances.

Can anyone help or point me to some detailed examples of how to do this?

Many thanks.

**Comment by cowtowncoder** [comment]
Ok this might be something better handled via discussion groups (https://groups.google.com/forum/#!forum/jackson-user and https://gitter.im/FasterXML/jackson-databind), but here are some thoughts...

First of all, what is most often used with other formats -- ObjectMapper.convertValue() -- would not work, just because CSV module (along with some others like Protobuf and Avro modules) requires use of a format schema (`CsvSchema`), to indicate mapping between column indexes and property names. So, whereas with JSON you could use something like:

```
Pojo pojo = mapper.treeToValue(node, Pojo.class);
```

this isn't enough as there is no way to pass schema. This is something to improve, probably, as there is no fundamental reason why this could not be done, as actual functionality to use exists.
I will file an issue to see what could be added:

https://github.com/FasterXML/jackson-databind/issues/2797

Having said that, it is possible to "read" from `JsonNode`, and this is how conversion really work:

```
JsonParser p = jsonMapper.treeAsTokens(node); // any mapper, actually, node is not format-specific
Pojo p = mapper.readerFor(Pojo.class)
    .with(csvSchema)
    .readValue(p);
```

Does this make sense? I may be missing some step in the chain; let me know.
If you have some code to share (or details in process), that could help as well.

**Comment by g1ps** [comment]
Hi,

Thanks. I'm happy to be pointed at better places to ask, although I have been looking all over and not found those.

Currently I'm doing this kind of thing:
```
                // API call
                ...
		if (responseCode == HttpURLConnection.HTTP_OK) {
			StringBuilder response;
			try (BufferedReader in = new BufferedReader(new InputStreamReader(connection.getInputStream()))) {
				response = new StringBuilder();
				while ((readLine = in .readLine()) != null) {
					response.append(readLine);
				}
			}

			ObjectMapper objectMapper = new ObjectMapper();

			JsonNode jsonNode = objectMapper.readTree(response.toString());

			JsonNode nodeIssues = jsonNode.get("issues");
			ArrayNode arrayNode = (ArrayNode) nodeIssues;
			for(int i = 0; i < arrayNode.size(); i++) {
				JsonNode arrayElement = arrayNode.get(i);
				JsonNode nodeFields = arrayElement.get("fields");

				// toString vs asText?
				csv += arrayElement.get("key").asText()+ this.separator;
                       ...
                 }
                 ...
         }
```
and that works but I haven't been able to understand at all how the schema/csv approach works and the docs aren't detailed enough. I did make forays into creating schema classes to specify and ignore fields but couldn't make it work and I still have no idea how that approach can be made to handle all of the nested data. Again, not enough information came to hand.

Many thanks.

**Comment by cowtowncoder** [comment]
Oh. Let's start with reading: no need to read and buffer text, just read from input stream as JsonNode:

```
JsonNode jsonNode = objectMapper.readTree(connection.getInputStream());
```

(buffering uses memory, cpu time, and unless you need content for something else [logging?], really adds no benefits)

As to schema: CSV is positional and thereby going from JsonNode or Map, it is necessary to know which column value for specific name goes. This what `CsvSchema` is for; one can create it from a POJO (either alphabetic [default], or explicit `@JsonPropertyOrder`), or manually.
These are explained on CSV module README:

https://github.com/FasterXML/jackson-dataformats-text/tree/master/csv

which I would expect you found earlier when searching for documentation.

Beyond this please use mailing list and/or Gitter chat: I do not have time for one-on-one usage tutorial, especially via Issue Tracker that is meant for reporting issues or requesting features.

**Comment by g1ps** [comment]
Thank you, will do and I'll try this today.
