### ISSUE TITLE
Deserialize value with JsonProperty

### ISSUE THREAD

**Issue by caiqfrog** [FasterXML/jackson-dataformats-text#216]
show my code.
```
class Prop {
 @JsonProperty("spark.task.cpus")
  var cpus: Int = 1
}
val text = "spark.task.cpus=6"
val result = mapper.readValue(text, Prop::class.java)
assert(result.cpus == 6)
```
Assertion failed.
But when i Serialize from POJO, it write to "spark.task.cpus=1"

**Comment by cowtowncoder** [comment]
I assume this is related to Java Properties format module (with... Scala?).

The problem is that `@JsonProperty` can not define hierarchy; name would be used exactly as-is. But with default settings Properties backend would treat dots as separators.
So the way module sees content would be equivalent to JSON content of

```
{ "spark":{
  "task":{
      "cpus" : 6
   }
}}
```

but with annotation, content expected would be

```
{ "spark.task.cpus":6}
```

If you want dots to be ignored, however (or use some other separator), you need to specify `JavaPropsSchema` to use. Something like:

```java
// disable use of "." as path separator
JavaPropsSchema schema = JavaPropsSchema.emptySchema()
   .withPathSeparator("");
ResultType result = mapper.readerFor(ResulType.class)
    .withSchema(schema)
   .readValue(input);
```

There is no way to currently indicate that `@JsonProperty` name should be converted to path, unfortunately.

**Comment by caiqfrog** [comment]
It works. Thanks!
the language is kotlin.
