### ISSUE TITLE
Cannot parse YAML into a list of sealed classes

### ISSUE THREAD

**Issue by martynamaron** [FasterXML/jackson-dataformats-text#275]
I'm trying to parse this simple YAML, which is effectively a list of objects that map to my sealed class implementations:
```yaml
- greeting: Hello
- statement: I'm awake
- greeting: Hi
- statement: It's a good day
```

Here are my sealed classes:
```kotlin
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME)
sealed class Message {
    data class Greeting(val greeting: String) : Message()
    data class Statement(val statement: String) : Message()
}
```
I'm using `@JsonTypeInfo` [as recommended for sealed classes](https://github.com/FasterXML/jackson-module-kotlin#sealed-classes-without-jsonsubtypes)

The way I'm trying to read the YAML is included in this test:
```kotlin

    @Test
    fun parseSimpleYaml_returnsCorrectResults() {

        val yamlObjectMapper = ObjectMapper(YAMLFactory()).registerModule(KotlinModule())
        val messages = yamlObjectMapper.readValue(simpleYaml, object: TypeReference<List<Message>>(){})

        val expectedMessages =
            listOf(
                Message.Greeting("Hello"),
                Message.Statement("What's up"),
                Message.Greeting("Hi"),
                Message.Statement("G'Day")
            )

        assertEquals(expectedMessages, messages)
    }
```

However, I get the following exception:
```
com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Missing type id when trying to resolve subtype of [simple type, class com.xx.xx.test.shared.Message]: missing type id property '@type'
 at [Source: (StringReader); line: 2, column: 1] (through reference chain: java.util.ArrayList[0])
```

I'd read about `@JsonTypeInfo` and `@JsonTypeName` annotations, but can't seem to be able to get around the `InvalidTypeIdException`.  How do I go about parsing the YAML file into sealed classes?

I raised the same issue in https://github.com/FasterXML/jackson-module-kotlin/issues/463

**Comment by martynamaron** [comment]
Update:

I managed to get _serialisation_ work, with some Jackson annotations, where the resulting YAML is what I'm using in the first place:

```kotlin
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type")
@JsonSubTypes(
    JsonSubTypes.Type(value = Message.Greeting::class, name = "greeting"),
    JsonSubTypes.Type(value = Message.Statement::class, name = "statement")
)
sealed class Message {

    @JsonTypeName("greeting")
    data class Greeting(val greeting: String) : Message()

    @JsonTypeName("statement")
    data class Statement(val statement: String) : Message()
}
```

```kotlin
        val messages =
            listOf(
                Message.Statement("Hello"),
                Message.Greeting("I'm awake"),
                Message.Statement("Hi"),
                Message.Greeting("It's a good day")
            )

val yaml = ObjectMapper(YAMLFactory()).registerModule(KotlinModule()).writeValueAsString(messages)
```

The `yaml` string is then:
```yaml
---
- statement: "Hello"
- greeting: "I'm awake"
- statement: "Hi"
- greeting: "It's a good day"
```

But **de-serialisation** doesn't work the other way around, using `readValue(yaml, object : TypeReference<List<Message>>() {})` on the ObjectMapper :( The exception I get is:

```
com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Missing type id when trying to resolve subtype of [simple type, class com.xx.xx.test.shared.Message]: missing type id property 'type'
 at [Source: (StringReader); line: 3, column: 1] (through reference chain: java.util.ArrayList[0])
```

**Comment by yawkat** [comment]
Your serialization works by accident. From what I can tell, it's not serializing the objects as `Message` instances at all, but rather as individual `Greeting` or `Statement` instances, because you don't provide any type info in the `writeValueAsString` call. With your current annotations, you'd expect a `"type": "greeting"` field on each object, which you don't have.

You won't get your expected behavior with Id.NAME. I think `JsonTypeInfo.Id.DEDUCTION` does what you want, though.

**Comment by martynamaron** [comment]
@yawkat Thank you so much for this! You're right, using:
```kotlin
@JsonTypeInfo(use = JsonTypeInfo.Id.DEDUCTION)
@JsonSubTypes(
    JsonSubTypes.Type(value = Message.Greeting::class, name = "greeting"),
    JsonSubTypes.Type(value = Message.Statement::class, name = "statement")
)
```
on the base class, without the individual `@JsonTypeName` annotations indeed does what I need when de-serialising the given YAML snippet

Thanks again! 🙌🏻

**Comment by cowtowncoder** [comment]
@martynamaron I would sort of echo what @yawkat suggests, that the issue you had is more worked around than solved by use of `DEDUCTION` style -- problem is specifically that upon serialization, passing a `List` value means that detected type is `List<?>` which is about same as `List<Object>`. Since `Object` is not handled in polymorphic way by default, no Type Id is added.

However, when READING you are asking for `List<Message>` (correctly), and `Message` DOES expect (require) Type Id.

Using `DEDUCTION` means that no Type Id is written or read, and that can be a really good way of doing things.
But it has some limitations (basically set of properties for subtypes must be distinct), so if you did have to use actual type id, you'd have to ensure writing uses full List typing. 
There are 2 common ways to do it:

1. Use a helper type like `class MessageList extends ArrayList { }` -- this retains full type info even for serialization
2. Construct `ObjectWriter` with type: `ObjectMapper.writerFor(new TypeReference<List<Message>>() { })` and use that for writing. This will write Type Ids as expected.

So this in case you run into trouble (or if anyone else is looking for solution).
