### ISSUE TITLE
jackson-dataformats-csv: copy over recent jackson-core changes

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-dataformats-text#312]
jackson-dataformats-csv has its own copy of jackson-core NumberInput and TextBuffer classes.

jackson-core changes that could be of use include:

* https://github.com/FasterXML/jackson-core/issues/577
* https://github.com/FasterXML/jackson-core/issues/514
* https://github.com/FasterXML/jackson-core/pull/757

**Comment by pjfanning** [comment]
@cowtowncoder thanks for merging the fast parser/generator support - this issue also includes https://github.com/FasterXML/jackson-core/pull/757 - is that worth pursuing? That remaining issue was the one where some edge case floats are not parsed correctly because they are first parsed as doubles and then cast to float instead of being parsed explicitly as floats (2 conversions when there should just be 1).

**Comment by cowtowncoder** [comment]
@pjfanning np, thank you for all these cool contributions.

As to remaining edge cases, yes, I think those would be good to address. Or at very least add (failing) tests cases where necessary. Then we could see how easy fixes are.

I also hope to get Jackson 3.0 development back on track. The one blocking thing right now is that I want to fully decide actual Java Package and Maven group ids.
My earlier idea of just doing `jackson` -> `jackson3` replacement is changing a bit; now I am leaning towards using a new domain, most likely `tools.jackson` (over `com.fasterxml`).
But once I figure out the choice there, I can finally start moving packages, so that:

1. `jackson-annotations` remains exactly as-is, as the sole exception. This means 2.x and 3.x will basically remain in-sync and there should be no need for annotation duplication (unlike with 1.x->2.0 transition)
2. `jackson-core` will move first, get published, and basically almost every other package must be modified (and re-published) by changing imports. That's lots of work and I don't want to do it many times
3. `jackson-databind` is next, similarly necessitating lots of work.
4. ... and so on for dataformats, datatypes, modules.

Oh yeah, Jackson 3.x really has no relevance to all parser work here. Just something I'll mention as relative near-term focus, possibly competing with 2.14 release. But I also do want to get 2.14.0 out quite soon -- all the must-haves I had are in (basically just the new `DataTypeFeature` -- although I think I do want to get "databind" issue 3054 implemented too).

**Comment by pjfanning** [comment]
@cowtowncoder I think this can be marked as resolved now
