### ISSUE TITLE
2.14 release timeline

### ISSUE THREAD

**Issue by oppegard** [FasterXML/jackson-dataformats-text#349]
First, thank you to the maintainers of this project!

Is there a timeline for releasing `jackson-dataformat-yaml` 2.14? Our security team runs a scanner that reported a CVE on the transitive snakeyaml dependency. We'd like to address the issue by bumping to a new version of `jackson-dataformat-yaml` that includes the updated snakeyaml.

**Comment by cowtowncoder** [comment]
@oppegard Instead of waiting for 2.14, I suggest you overriding `snakeyaml` dependency directly. Later versions are API compatible.
This is also necessary because we seem to get a snakeyaml version released on almost weekly basis thanks sec researching dropping their CVEs.

2.14.0-rc1 is out by now, but I anticipate needing to do rc2 so the official 2.14.0 is couple of weeks out.

**Comment by oppegard** [comment]
Thank you for the suggestion @cowtowncoder, and for your estimate on a 2.14.0 timeline.

**Comment by cowtowncoder** [comment]
No problem @oppegard & good luck!
