### ISSUE TITLE
[yaml]Redundant double quotation marks and newline characters show up after deseralizing yaml string and serializing back to yaml string

### ISSUE THREAD

**Issue by Transi-ent** [FasterXML/jackson-dataformats-text#354]
my jackson-dataformat-yaml version is 2.13.2. In my code, I read yaml string into JsonNode, and do some processing to JsonNode object, then i serialize the JsonNode back into yaml, but redundant double quotation marks and newline characters show up.

my code maybe like this:
```java
YAMLMapper yamlMapper= new YAMLMapper(new YAMLFactory())
            .disable(YAMLGenerator.Feature.SPLIT_LINES)
            .configure(MINIMIZE_QUOTES, true);
JsonNode jsonNode = yamlMapper.readTree(content);
// do some processing to jsonNode
String newContent = yamlMapper.writeValueAsString(jsonNode);
```
content look like below (part of a swagger API file):
```yaml
responses:
    '200':
      description: successful operation
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/MyResponseBody"
          example:
            {
              "sites": [
              {
                "name": "test",
                "updated_at": null
              }],
              "page_info": {
                "current_count": 1
              }
            }
```
newContent look like this:
```yaml
responses:
    "200":
      description: successful operation
      content:
        application/json:
          schema:
            $ref: #/components/schemas/MyResponseBody
          example:
            sites:
            - name: test
              updated_at: "null\r"
            page_info:
              current_count: "1\r"
```
I have tried 2.14.0, but got the same result.
Am i missing some options when using this? thanks very much~ Orz.

**Comment by cowtowncoder** [comment]
I think it would be good to try to create minimal reproductions of issues for different aspects. Looks like handling of `$ref`, for example, might be actually missing necessary quotes (and becomes a comment). But as to `null` and `1` it seems like SnakeYAML parser might be including those in textual values so that they are not actually Boolean/Number values but text with trailing `\r` character; and if so, to reproduce them exactly as-is, must be serialized quoted with trailing `\r` character.
I am not sure why this second thing occurs; perhaps because YAML is using odd combination of markups (YAML "natural" first, then JSON-like alternative syntax later on).

**Comment by Transi-ent** [comment]
thank you for the constructive feedback @cowtowncoder, it seems that there is some problems with my self-defined yamlParser.

**Comment by Transi-ent** [comment]
end
