### ISSUE TITLE
(csv) uppercase fields issue

### ISSUE THREAD

**Issue by pimuzzo** [FasterXML/jackson-dataformats-text#49]
I've a field all uppercase, called SKU.
If I set the field as public, all works well.
If i set the field private with getters and setters, the column isn't populated.
If needed I can try to reproduce it in your tests.

I'm using v. 2.8.8 but I've reproduced also with the 2.9.0

**Comment by cowtowncoder** [comment]
Yes, a reproduction would be needed here. But one thing I'd suggest trying first is:

    mapper.enable(MapperFeature.USE_STD_BEAN_NAMING);

since that is needed to match fields with getters/setters: Jackson default name mangling differs with standard bean naming in cases of more than one leading upper case letter (for method names).
So depending on how setters/getters are named, this setting might be the root cause.
For Jackson 3.x standard naming will be the default (and only choice); for 2.x this setting is needed for backwards compatibility.

**Comment by pimuzzo** [comment]
Thank you, your suggestion fixed my issue.
