### ISSUE TITLE
Support for isRequired (mandatoriness) check

### ISSUE THREAD

**Issue by sachinlala** [FasterXML/jackson-dataformats-text#52]
**Background**:
We're in need for a fast and feature-rich CSV Parser and have zeroed-in on using jackson-dataformats-text library. We will be passing the 'Schema' object as an input (which is populated from a schema-file we receive from an upstream system). For each field, we will provide a 'Name' and 'Data Type'. Additionally, we would like to provide an input 'isRequired' so if a field is marked isRequired=true but there is no data in that field in the incoming CSV file, we need to raise an exception.

**Requirement**:
So far, we could not find support for 'isRequired' check. Please can you advise if this is already present or if not, could this be taken as a new requirement to add the feature in an upcoming release ?

Thanks.

**Comment by cowtowncoder** [comment]
Required-ness check would have to be added in `jackson-databind`, as format modules do not have information available. It is a long-standing request:

https://github.com/FasterXML/jackson-databind/issues/230

As things are, checks are only implemented for one special case: Creator properties. So if you define constructor or factory method like:

    @JsonCreator
    public MyType(@JsonProperty(required=true) String name), ....)

verification is made. Otherwise, if only passing via setters or assigned to fields, no check is made.

Challenge in this case is simply complexity of adding explicit state and tracking for properties; added overhead, and avoiding the overhead if no checks are needed. So it is a large undertaking. Perhaps it could be implemented for 3.0: this is something many users have requested.

**Comment by cowtowncoder** [comment]
Since this is covered by issue I linked to, will close this issue: I think support needs to go in databind and not dataformat modules. So closing issue here as a duplicate.
