### ISSUE TITLE
(yaml) Possible performance regression in snakeyaml 1.18

### ISSUE THREAD

**Issue by tlrx** [FasterXML/jackson-dataformats-text#67]
Hi,

I spotted a performance regression in snakeyaml introduced in version 1.18+. This issue has been reported on the snakeyaml mailing list [here](https://groups.google.com/d/msg/snakeyaml-core/y8bKgDdZwuQ/s05OhvEvCgAJ) and seems to affect the parsing of large text values.

It affects `jackson-dataformats-text` starting version 2.9.1 as it depends on snakeyaml 1.18. Version 1.19 is also problematic but version 1.17 is ok.

I understand that this is not a `jackson-dataformats-text` issue but I'd like 1) to raise awareness on this regression and 2) to ensure that `jackson-dataformats-text` dependency on snakeyaml will be updated to a newer version that fixes the regression (if such version is released)

**Comment by cowtowncoder** [comment]
Ok. Thank you for reporting this. I don't remember if `1.18` was specifically needed for a bug fix or not. If not, could gracefully downgrade until 1.20 (or whatever with fix) comes along.

It is too bad SnakeYAML has severe performance issues in general (it's literally 10-20x slower than, say, json parsing, or 10x xml); otherwise it works very well.

**Comment by chrisco484** [comment]
"10x [slower than] xml [parsing]?"

With XML being so verbose it's hard to imagine anything being slower than XML parsing. That's amazing.

**Comment by cowtowncoder** [comment]
@chrisco484 there is no fundamental reason it should be, since at low level textual codecs really should converge to similar speeds relative to raw size (that is, more verbose formats would be bit slower just since there's more text to decode). On the other hand, XML parsers have been rather aggressively optimized so parsers like Aalto get pretty decent throughput, in 10s of megabytes per second per core. It would be nice if YAML part could be improved.

**Comment by chrisco484** [comment]
Yes, I guess the XML world has had 20 years to optimize whereas YAML is
relatively recent in its ever growing adoption.

 

The theoretical max speed of any YAML parser should be quicker than the
theoretical max speed of any XML parser given YAML doesn't have the
verbosity of XML but, as you say, the difference may not be large - but
still would be noticeable on larger data sets I would think.

 

________________________________

**Comment by cowtowncoder** [comment]
Right. And one problem with YAML is that the rules for decoding are rather complicated (specification is huge, and with all the variations to support wiki-style, or not, it gets hairy quick), which makes it much more work to optimize.
But I don't think that's where most of the time is spent right now: I think it's just `SnakeYAML` using quite complex processing pipeline.

As long as YAML is mostly used for configuration handling this isn't much of a problem.
But it could be a problem for anyone using YAML for data interchange (request/response).

**Comment by chrisco484** [comment]
yeah, i was thinking of using it for data integration/migration because
of Yaml's smaller serialised output.

 

________________________________

**Comment by cowtowncoder** [comment]
@tlrx Looks like `1.20` is out. Not sure if that differs from `1.19` in this aspect.

**Comment by 40ft** [comment]
I just ran into this performance problem (parsing a 30KB string on Android) and spent a couple of hours looking at the snakeyaml code, before finding my way here.

The main problem in 1.18 is a O(n-squared) loop in the Reader.peek() function, which has indeed been completely rewritten and fixed in later versions. Forcing snakeyaml to 1.21 (with jackson 2.9.5) in my build gives acceptable parsing performance on Android. It does break serialization though, as mentioned above.

Generally speaking, there is a _lot_ of seemingly unnecessary string buffering/duplication/copying going on in the snakeyaml parsing code (optimisation is hard!), so I am not at all surprised if performance is bad.

**Comment by asomov** [comment]
@chrisco484 : the YAML 1.2 spec is very big. Chomping, flow styles, scalar styles (especially the literal style), implicit types, anchors/aliases/recursive structures, complex keys are not present in XML and they are not often used. Nevertheless the parser must always take care of all these details.

**Comment by asomov** [comment]
@yborovikov: can I help to adapt jackson 2.9.5 to work with SnakeYAML 1.21 ?

**Comment by cowtowncoder** [comment]
Quick note: next patch version would be `2.9.6`, but I have decided that there probably should be minor upgrade of 2.10 for Jackson, before bigger changes in 3.0.

I have no objections to changes in 2.9(.6) that allow use of newer version (and dependency to newer version), as long as change would still work with older version(s) that Jackson 2.9 has relied on.
This because users sometimes have slightly inconsistent set of dependencies, and I don't want to add risk in patch versions.

For 2.10, new version should definitely be used, so above caveat is only wrt 2.9.x patches.

**Comment by yborovikov** [comment]
@asomov Theoretically, reinstating the `ScalarEvent(String anchor, String tag, ImplicitTuple implicit, String value, Mark startMark, Mark endMark, Character style)` constructor (and marking it as `@Deprecated`) should restore `snakeyaml`'s compatibility with `jackson`'s `YAMLGenerator`.

This way Jackson `2.9.x` would be able to use both older and newer versions of snakeyaml (with the exception of `1.20` and `1.21`).

**Comment by asomov** [comment]
I am confused now. I thought that this issue is all about migrating to SnakeYAML 1.21

**Comment by cowtowncoder** [comment]
SnakeYAML version was upgraded, as per #81, so I think this is resolved now.
