### ISSUE TITLE
YAML as tree (ObjectNode) with Kotlin and anchoring

### ISSUE THREAD

**Issue by Sokolowski-Michal-Piotr** [FasterXML/jackson-dataformats-text#85]
Having such piece of code:
```
val doc = "k1: &ref 123\nk2: *ref"
val snake = Yaml().load(doc)
val jackson = ObjectMapper(YAMLFactory()).readTree(doc)

println((snake as Map<String, Int>)["k2"])
println(jackson["k2"].asInt())
```
It produces following output:
```
123
0
```
If I'm not wrong jackson's output is invalid. Why? Am I missing something?

**Comment by cowtowncoder** [comment]
Jackson only supports Object Ids, references (anchors) when POJO model specifies need for it (`@JsonIdentityInfo`). And there is no way to either map references to tree model (`JsonNode`), and given that tree model can not have cycles this could not work even theoretically.

So this is use case that is not and will not be supported. For object references, POJOs must be used, with proper references.

Now... in theory, references to scalar types could perhaps be supported. But since that would cause difference between structured and scalar types (as former can not be supported) I am not sure that would be useful.

**Comment by cowtowncoder** [comment]
No simple fix exists here; for bigger work to support handling of Anchors, a new issue with proposal (at high-level at least) should be filed.
