### ISSUE TITLE
Feature request for SnakeYAML

### ISSUE THREAD

**Issue by asomov** [FasterXML/jackson-dataformats-text#87]
Hi all, we are completely rewriting SnakeYAML (using YAML 1.2 and Java 8).
Are you interested in participating ?
What would you like to implement ? What should become better/different?

**Comment by cowtowncoder** [comment]
Hi! Thank you for notification here. A rewrite sounds good, and would align well with Jackson 3.0 requiring Java 8.

I wish I had a good list to give, but I think 2 general things seem like good things:

1. Performance: for some reason, parsing especially is quite slow. I do not have good understanding why this is -- I realize that due to large feature set of YAML (with anchors/refs, type tags) there is more work to do, and some information must be kept in memory (anchors to match with refs) that is not necessary ins JSON. But I don't think that explains much of it.
2. More convenient access to type ids (type tags). If possible, it would be great to have some added functionality that would expose type tags in something more refined than Strings. I don't know how possibly/easy this would be, since set is open ended. But creating some sort of wrapper object would seem useful.
3. More convenient access to anchors, refs. As with type tags, access as Strings works, but since there is probably bit more metadata available, would be nice to model these are first class objects maybe?
4. Configurability, similarly, maybe could be made easier and/or documented more.

I guess all around adding simple abstraction improvements might be helpful.
I know this is not very practical or actionable yet. If I can think of more specific things, I will add a note.

I really appreciate your reaching out!

**Comment by asomov** [comment]
Dear @cowtowncoder , if you make an account on [BitBucket](https://bitbucket.org)  I can give you the early access to the new project. You can review the code and propose any change. Once the API is satisfactory we can release the project.

**Comment by asomov** [comment]
Hi all,
the new project [SnakeYAML engine](https://bitbucket.org/asomov/snakeyaml-engine) is now available for evaluation.
Features:
- YAML 1.2
- Java 8
- new API (both low level and high level). Feedback is welcome !!!
- complete re-write
- JavaBeans are removed (they will be implemented in a separate project to keep the engine small and flexible)
- the SnakeYAML engine is not yet released in Maven central (2018-05-11).

To evaluate:
- Clone the project: 'hg clone https://asomov@bitbucket.org/asomov/snakeyaml-engine'
- Install locally 'mvn clean install'
- Check out branch: https://github.com/asomov/jackson-dataformats-text/tree/snakeyaml-engine
- Please help to fix the test failures there
- Feel free to review the code

**Comment by asomov** [comment]
The tests are now green

**Comment by cowtowncoder** [comment]
Ah cool. I will also try to raise awareness, I think it would be good to get more developers involved.
SnakeYAML is very good library and does a good job of supporting yaml spec and having strong community is important.

**Comment by asomov** [comment]
For me the integration of SnakeYAML Engine with jackson is finished - the tests are green.

@cowtowncoder: Feel free to contact me if you have questions. I think the branch can be merged.
